services:
  tadeot-frontend-201126:
    image: ghcr.io/syp-ahif-2024-25-26/tadeottools/frontend:latest
    container_name: tadeot-frontend-201126
    environment:
      - BACKEND_URL=https://tadeot.htl-leonding.ac.at/tadeot-backend-201126
    networks:
      - tadeotnet-201126
    depends_on:
      - tadeot-backend-201126

  tadeot-dashboard-201126:
    image: ghcr.io/syp-ahif-2024-25-26/tadeottools/dashboard:latest
    container_name: tadeot-dashboard-201126
    environment:
      - BASE_HREF=/adm-dashboard/
      - BACKEND_URL=https://tadeot.htl-leonding.ac.at/tadeot-backend-201126/v1
      - KEYCLOAK_REDIRECT_URI=https://tadeot.htl-leonding.ac.at/adm-dashboard/
    networks:
      - tadeotnet-201126
    depends_on:
      - tadeot-backend-201126

  tadeot-backend-201126:
    container_name: tadeot-backend-201126
    image: ghcr.io/syp-ahif-2024-25-26/tadeottools/backend:latest
    ports:
      - "4100:4100"
    restart: always
    networks:
      - tadeotnet-201126
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__DefaultConnection=Host=tadeot-postgres;Database=tadeot;Username=user;Password=test
      - ASPNETCORE_URLS=http://+:4100
    depends_on:
      tadeot-postgres:
        condition: service_healthy

  tadeot-postgres:
    image: postgres:17.7-bookworm
    container_name: tadeot-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=tadeot
    volumes:
      - tadeotvol-201126:/var/lib/postgresql/data
    networks:
      - tadeotnet-201126
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d tadeot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  tadeotnet-201126:
    external: true

volumes:
  tadeotvol-201126:
    external: true