services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: tadeot
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network
  
  adminer:
    image: adminer
    container_name: tadeot-tools-adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile:  Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge
    external: false
    ipam:
      config:
        - subnet: 10.2.0.0/16