services:

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/letsencrypt
    networks:
      - tadeotnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-api.rule=Host(`tadeot.htl-leonding.ac.at`)
      - traefik.http.routers.traefik-api.service=api@internal

networks:
  tadeotnet:
    external: false
    name: tadeotnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16