name: Deploy to VM

on:
  # Deploy after successful build and push
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main
  
  # Also allow manual deployment
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT || 22 }}
          script: |
            # Navigate to deployment directory
            cd ~/tadeot-2511
            
            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull latest images
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest  
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dashboard:latest
            
            # Stop and remove existing containers
            docker compose down
            
            # Start updated containers
            docker compose up --build -d
            
            # Clean up old images
            docker image prune -f
            
            # Show status
            docker compose ps
